services:
  - type: web
    name: zentrafuge-backend
    env: python
    buildCommand: cd backend && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT
    runtime: python
    pythonVersion: 3.10.13
