services:
  - type: web
    name: zentrafuge-backend
    env: python
    buildCommand: |
      cd backend
      pip install --upgrade pip setuptools wheel build
      pip install -r requirements.txt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT
    pythonVersion: 3.10.13
